name: Semgrep and Deploy Report

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  semgrep-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep --config p/javascript --json > semgrep-report.json

      # - name: Build Semgrep Report Page
      #   run: |
      #     mkdir report
      #     echo "<html><head><title>Semgrep Report</title></head><body><h1>Semgrep Scan Report</h1><pre>" > report/index.html
      #     cat semgrep-report.json >> report/index.html
      #     echo "</pre></body></html>" >> report/index.html

      - name: Build Semgrep Report Page
        run: |
          mkdir -p report
          cp semgrep-report.json report/semgrep-report.json

          cat > report/index.html <<'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Semgrep Report</title>
            <style>
              body { font-family: monospace; background: #f4f6f9; padding: 20px; color: #333; }
              .box { border: 2px solid #333; display: inline-block; padding: 5px 10px; margin-bottom: 10px; }
              .title { font-weight: bold; text-align: center; margin-bottom: 5px; }
              .section { margin-top: 20px; }
              .success { color: #28a745; font-weight: bold; }
              .error { color: #d9534f; font-weight: bold; }
              .summary p { margin: 2px 0; }
              table { border-collapse: collapse; width: 100%; margin-top: 20px; background: #fff; box-shadow: 0 2px 6px rgba(0,0,0,0.1); }
              th, td { padding: 10px; border: 1px solid #ddd; text-align: left; }
              th { background: #007acc; color: #fff; }
              tr:nth-child(even) { background: #f9f9f9; }
              .severity-error { color: #d9534f; font-weight: bold; }
              .severity-warning { color: #f0ad4e; font-weight: bold; }
              .severity-info { color: #5bc0de; font-weight: bold; }
            </style>
          </head>
          <body>
            <div class="box"><div class="title">Scan Status</div></div>
            <div class="section" id="status">
              <p>Scanning files tracked by git...</p>
            </div>

            <div class="box"><div class="title">Scan Summary</div></div>
            <div class="section summary" id="summary">
              <p>Loading report...</p>
            </div>

            <div class="section" id="details"></div>

            <script>
              fetch('semgrep-report.json')
                .then(res => res.json())
                .then(data => {
                  // Summary
                  const summaryEl = document.getElementById('summary');
                  const findings = data.results.length;
                  const rulesRun = data.rules ? data.rules.length : 'N/A';
                  const targets = data.targets_scanned || 'N/A';
                  summaryEl.innerHTML = `
                    <p>${findings === 0 ? '✅ Scan completed successfully.' : '❌ Findings detected!'}</p>
                    <p>• Findings: ${findings} (${findings} blocking)</p>
                    <p>• Rules run: ${rulesRun}</p>
                    <p>• Targets scanned: ${targets}</p>
                    <p>• Parsed lines: ~100.0%</p>
                    <p>• Scan was limited to files tracked by git</p>
                  `;

                  // Detailed table
                  const detailsEl = document.getElementById('details');
                  if (!data.results || data.results.length === 0) {
                    detailsEl.innerHTML = "<p>No findings 🎉</p>";
                    return;
                  }

                  let html = "<table><tr><th>Rule</th><th>Severity</th><th>Message</th><th>File</th><th>Line</th></tr>";
                  data.results.forEach(r => {
                    let sev = r.extra.severity || "info";
                    html += "<tr>" +
                              "<td>" + r.check_id + "</td>" +
                              "<td class='severity-" + sev.toLowerCase() + "'>" + sev + "</td>" +
                              "<td>" + r.extra.message + "</td>" +
                              "<td>" + r.path + "</td>" +
                              "<td>" + r.start.line + "</td>" +
                            "</tr>";
                  });
                  html += "</table>";
                  detailsEl.innerHTML = html;
                });
            </script>
          </body>
          </html>
          EOF


      # Upload artifact for Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./report

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: semgrep-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
