name: Semgrep and Deploy Report

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  semgrep-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep --config p/javascript --json > semgrep-report.json

      - name: Build Semgrep Report Page
        run: |
          mkdir report
          echo "<html><head><title>Semgrep Report</title></head><body><h1>Semgrep Scan Report</h1><pre>" > report/index.html
          cat semgrep-report.json >> report/index.html
          echo "</pre></body></html>" >> report/index.html

      # Upload artifact for Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./report

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: semgrep-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
